### ISSUE TITLE
can you please share sharded (<2gb / bin) model? 

### ISSUE THREAD

**Issue by amrrs** [deepseek-ai/DeepSeek-LLM#2]
Thanks for this. The 7B model can be fit in Google colab given there model are tiny pieces. 
Example: https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded

**Comment by luofuli** [comment]
The example link has been 404. And we don't have a plan to share the shaded model.  Therefore, I close the issue.

**Comment by amrrs** [comment]
For anyone else coming here, someone else on HF had already shared a sharded model - https://huggingface.co/notzero/deepseek_sharded/tree/main (I'm not sure of the legitimacy or the content of it, use at your own risk)
