### ISSUE TITLE
Will finetune scripts be provided?

### ISSUE THREAD

**Issue by ftgreat** [deepseek-ai/DeepSeek-LLM#23]

**Comment by DeepSeekPH** [comment]
Please refer this repo for more details. [DeepSeek-LLM/finetune/finetune.py at finetune_patch · zwd973-deepseek/DeepSeek-LLM (github.com)  ](https://github.com/zwd973-deepseek/DeepSeek-LLM/blob/finetune_patch/finetune/finetune.py)   

It will be merged soon.
