### ISSUE TITLE
关于System Prompt

### ISSUE THREAD

**Issue by DirtyKnightForVi** [deepseek-ai/DeepSeek-LLM#28]
首先感谢你们的优秀开源工作！

在你们发布的技术报告中提到的System Prompt，与你们在DeepSeek coder模板中的第一句提示词接近。

不过，在你们发布的67B的chat模型中，我检查了你们发布的tokenizer_config.json，发现模板中没有位置加入这个提示词。

请问System Prompt应该是加在哪里呢？
另外你们有function call或者agent版本的模型开发计划吗？

**Comment by stack-heap-overflow** [comment]
感谢您对我们工作的关注。

实际上，我们在`tokenizer_config.json`的`chat_template`中已经预留了System Prompt的位置：

"chat_template": "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{{ bos_token }}{% for message in messages %}{% if message['role'] == 'user' %}{{ 'User: ' + message['content'] + '\n\n' }}{% elif message['role'] == 'assistant' %}{{ 'Assistant: ' + message['content'] + eos_token }}**{% elif message['role'] == 'system' %}{{ message['content'] + '\n\n' }}{% endif %}**{% endfor %}{% if add_generation_prompt %}{{ 'Assistant:' }}{% endif %}"

在使用时需要保证system消息唯一且位于第一条的位置就能得到符合我们预期的结果。

**Comment by DirtyKnightForVi** [comment]
> 感谢您对我们工作的关注。
> 
> 实际上，我们在`tokenizer_config.json`的`chat_template`中已经预留了System Prompt的位置：
> 
> "chat_template": "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{{ bos_token }}{% for message in messages %}{% if message['role'] == 'user' %}{{ 'User: ' + message['content'] + '\n\n' }}{% elif message['role'] == 'assistant' %}{{ 'Assistant: ' + message['content'] + eos_token }}**{% elif message['role'] == 'system' %}{{ message['content'] + '\n\n' }}{% endif %}**{% endfor %}{% if add_generation_prompt %}{{ 'Assistant:' }}{% endif %}"
> 
> 在使用时需要保证system消息唯一且位于第一条的位置就能得到符合我们预期的结果。

在coder 33B这个模型上其实也有实验过：
你们的found_item参数似乎无法起作用。不管我的system是否设置了，模型还是会将默认的“you are a AI programming assistant ···”这个提示词一起输出。

虽然我也注意到你们更新了tokenizer_config.json，里面抛弃了这个参数。

**Comment by stack-heap-overflow** [comment]
在包括Tokenizer在内的部分实现细节上，chat和coder模型并不完全一致。使用不同模型时请以对应模型的`chat_template`为准。在chat模型中并没有默认指定System Prompt，如有需要可以自行在消息列表中添加。

**Comment by DirtyKnightForVi** [comment]
> 在包括Tokenizer在内的部分实现细节上，chat和coder模型并不完全一致。使用不同模型时请以对应模型的`chat_template`为准。在chat模型中并没有默认指定System Prompt，如有需要可以自行在消息列表中添加。

我的意思是：在之前coder对应的`chat_template`里，带了一个叫做`found_item`的参数，以此来控制System Prompt。
在此基础上，我发现他确实能把`用户自定义的System Prompt`信息带进去，但是仍然会输出你们预先设置的提示词
`“you are a AI programming assistant ···”`。这意味着两个system prompt。

如图
![Uploading 微信图片_20240109171225.jpg…]()

**Comment by suncheng-s** [comment]
请问，后面有找到原因吗？
